//
//  Localized.swift
//  Generated by LocalizeDecoder
//
//  This file contains localization keys for mapping within Localizable.xcstrings
//

struct Localized {

   struct Backlog {
      static let menuCategories = "_backlog.menu_categories"
   }

   struct Badge {
      static let live = "badge.live"
      static let new = "badge.new"
   }

   struct ContentDetail {
      static let addedListButton = "content_detail.added_list_button"
      static let collectionTab = "content_detail.collection_tab"
      static let continueEpisodeButton = "content_detail.continue_episode_button"
      static let continueSeasonEpisodeButton = "content_detail.continue_season_episode_button"
      static let continueWatchingButton = "content_detail.continue_watching_button"
      static let creditButton = "content_detail.credit_button"
      static let episodeTab = "content_detail.episode_tab"
      static let eventTab = "content_detail.event_tab"
      static let moreEpisodeButton = "content_detail.more_episode_button"
      static let moreLikeThisButton = "content_detail.more_like_this_button"
      static let myListButton = "content_detail.my_list_button"
      static let partner = "content_detail.partner"
      static let relatedListTab = "content_detail.related_list_tab"
      static let remaining = "content_detail.remaining"
      static let remindMeButton = "content_detail.remind_me_button"
      static let reminderSetButton = "content_detail.reminder_set_button"
      static let removedContinueWatchingButton = "content_detail.removed_continue_watching_button"
      static let removedListButton = "content_detail.removed_list_button"
      static let season = "content_detail.season"
      static let seasons = "content_detail.seasons"
      static let shareButton = "content_detail.share_button"
      static let subtitlesButton = "content_detail.subtitles_button"
      static let trailerAndMoreTab = "content_detail.trailer_and_more_tab"
      static let watchEpisodeButton = "content_detail.watch_episode_button"
      static let watchLiveButton = "content_detail.watch_live_button"
      static let watchNow = "content_detail.watch_now"
      static let watchSeasonEpisodeButton = "content_detail.watch_season_episode_button"
      static let watchedFromBeginningButton = "content_detail.watched_from_beginning_button"

      struct MoreInfo {
         static let cast = "content_detail.more_info.cast"
         static let castMobile = "content_detail.more_info.cast_mobile"
         static let director = "content_detail.more_info.director"
         static let directorMobile = "content_detail.more_info.director_mobile"
         static let genres = "content_detail.more_info.genres"
         static let marutiryRating = "content_detail.more_info.marutiry_rating"
         static let moreButton = "content_detail.more_info.more_button"
         static let movieRatingG = "content_detail.more_info.movie_rating_g"
         static let movieRatingNc17 = "content_detail.more_info.movie_rating_nc17"
         static let movieRatingPg = "content_detail.more_info.movie_rating_pg"
         static let movieRatingPg13 = "content_detail.more_info.movie_rating_pg13"
         static let movieRatingR = "content_detail.more_info.movie_rating_r"
      }

      struct MyLists {
         static let addedToYourList = "content_detail.my_lists.added_to_your_list"
         static let reminderCanceled = "content_detail.my_lists.reminder_canceled"
         static let reminderSet = "content_detail.my_lists.reminder_set"
         static let reminderSetLive = "content_detail.my_lists.reminder_set_live"
         static let removeYourList = "content_detail.my_lists.remove_your_list"
         static let unableToAdd = "content_detail.my_lists.unable_to_add"
         static let unableToRemove = "content_detail.my_lists.unable_to_remove"
      }
   }

   struct Date {
      static let today = "date.today"
      static let tomorrow = "date.tomorrow"
   }

   struct HelpSettings {
      static let accountSettings = "help_settings.account_settings"
      static let device = "help_settings.device"
      static let termsAndConditions = "help_settings.terms_and_conditions"
      static let title = "help_settings.title"
      static let titleDescription = "help_settings.title_description"

      struct AccountSettings {
         static let title = "help_settings.account_settings.title"
         static let titleDescription = "help_settings.account_settings.title_description"
      }

      struct Button {
         static let agreeButton = "help_settings.button.agree_button"
         static let backButton = "help_settings.button.back_button"
         static let declineButton = "help_settings.button.decline_button"
         static let logoutButton = "help_settings.button.logout_button"
      }

      struct Device {
         static let deviceModel = "help_settings.device.device_model"
         static let platformVersion = "help_settings.device.platform_version"
         static let softwareVersion = "help_settings.device.software_version"
         static let title = "help_settings.device.title"
         static let titleDescription = "help_settings.device.title_description"
      }

      struct TermsAndConditions {
         static let title = "help_settings.terms_and_conditions.title"
         static let titleDescription = "help_settings.terms_and_conditions.title_description"
      }
   }

   struct Language {
      static let en = "language.en"
      static let my = "language.my"
      static let th = "language.th"
   }

   struct LiveTv {
      static let digitalTv = "live_tv.digital_tv"
      static let recentlyWatched = "live_tv.recently_watched"
      static let shopping = "live_tv.shopping"
      static let sports = "live_tv.sports"
      static let today = "live_tv.today"

      struct LivePlayer {
         static let catchupBadge = "live_tv.live_player.catchup_badge"
         static let catchupTab = "live_tv.live_player.catchup_tab"
         static let episodesTab = "live_tv.live_player.episodes_tab"
         static let liveBadge = "live_tv.live_player.live_badge"
         static let noProgramData = "live_tv.live_player.no_program_data"
         static let processingStatus = "live_tv.live_player.processing_status"
         static let schedulesTab = "live_tv.live_player.schedules_tab"
         static let subscribeToWatchButton = "live_tv.live_player.subscribe_to_watch_button"
      }
   }

   struct MaturityRating {
      static let descAdult = "maturity_rating.desc_adult"
      static let descKids = "maturity_rating.desc_kids"
      static let descTeen = "maturity_rating.desc_teen"
      static let description = "maturity_rating.description"
      static let rateAdult = "maturity_rating.rate_adult"
      static let rateKids = "maturity_rating.rate_kids"
      static let rateTeen = "maturity_rating.rate_teen"
      static let text = "maturity_rating.text"
      static let title = "maturity_rating.title"
      static let trailer = "maturity_rating.trailer"
   }

   struct Modal {

      struct Button {
         static let back = "modal.button.back"
         static let cancel = "modal.button.cancel"
         static let close = "modal.button.close"
         static let logIn = "modal.button.log_in"
         static let refresh = "modal.button.refresh"
         static let tryAgain = "modal.button.try_again"
      }

      struct ClosedApp {
         static let closedAppButton = "modal.closed_app.closed_app_button"
         static let desc = "modal.closed_app.desc"
         static let title = "modal.closed_app.title"
      }

      struct DeleteProfile {
         static let deleteProfileButton = "modal.delete_profile.delete_profile_button"
         static let title = "modal.delete_profile.title"
         static let titleDescription = "modal.delete_profile.title_description"
      }

      struct Language {
         static let titleModal = "modal.language.title_modal"
      }

      struct Logout {
         static let desc = "modal.logout.desc"
         static let logoutButton = "modal.logout.logout_button"
         static let title = "modal.logout.title"
      }

      struct ScanQr {
         static let desLoggedInSucce = "modal.scan_qr.des_logged_in_succe"
         static let desQrError = "modal.scan_qr.des_qr_error"
         static let titleLoggedInSucce = "modal.scan_qr.title_logged_in_succe"
         static let titleQrError = "modal.scan_qr.title_qr_error"
      }

      struct SomethingWentWrong {
         static let loadSettings = "modal.something_went_wrong.load_settings"
         static let searchDesc = "modal.something_went_wrong.search_desc"
         static let title = "modal.something_went_wrong.title"
         static let tryAgainLater = "modal.something_went_wrong.try_again_later"
      }

      struct Subscribe {
         static let desc = "modal.subscribe.desc"
         static let error = "modal.subscribe.error"
         static let title = "modal.subscribe.title"
      }

      struct SubtitlesAudio {
         static let audio = "modal.subtitles_audio.audio"
         static let subtitle = "modal.subtitles_audio.subtitle"
      }
   }

   struct NewOnNow {
      static let myListButton = "new_on_now.my_list_button"
      static let remindMeButton = "new_on_now.remind_me_button"
      static let reminderSetButton = "new_on_now.reminder_set_button"
      static let watchNowButton = "new_on_now.watch_now_button"
   }

   struct OnBoarding {
      static let loginButton = "on_boarding.login_button"
   }

   struct Player {
      static let length = "player.length"
      static let length1 = "player.length_1"
      static let live = "player.live"
      static let nextEpisodeButton = "player.next_episode_button"
      static let nextepisodein5seconds = "player.nextepisodein5seconds"
      static let skipIntroButton = "player.skip_intro_button"
      static let skipRecapButton = "player.skip_recap_button"
      static let text = "player.text"
      static let text1 = "player.text_1"
      static let text2 = "player.text_2"
      static let watchLiveButton = "player.watch_live_button"

      struct Cast {
         static let selectADevice = "player.cast.select_a_device"
      }

      struct EndCredit {
         static let nextEpisodeIn = "player.end_credit.next_episode_in"
         static let seconds = "player.end_credit.seconds"
         static let watchCredits = "player.end_credit.watch_credits"
      }

      struct Season {
         static let epNumber = "player.season.ep_number"
         static let min = "player.season.min"
         static let seasonTitle = "player.season.season_title"
         static let selectSeason = "player.season.select_season"
      }

      struct SettingMenu {
         static let audioSubtitles = "player.setting_menu.audio_subtitles"
         static let detail = "player.setting_menu.detail"
         static let episodes = "player.setting_menu.episodes"
         static let episodes2 = "player.setting_menu.episodes_2"
         static let info = "player.setting_menu.info"
         static let nextEp = "player.setting_menu.next_ep"
         static let speed = "player.setting_menu.speed"

         struct AudioSubtitlesMenu {
            static let audio = "player.setting_menu.audio_subtitles_menu.audio"
            static let subtitles = "player.setting_menu.audio_subtitles_menu.subtitles"
         }

         struct SpeedMenu {
            static let speed = "player.setting_menu.speed_menu.speed"
         }
      }
   }

   struct Prefix {
      static let episode = "prefix.episode"
      static let season = "prefix.season"
   }

   struct ProfileDisplay {

      struct AddProfile {
         static let createButton = "profile_display.add_profile.create_button"
         static let inputErrorCharacters = "profile_display.add_profile.input_error_characters"
         static let inputErrorEmpty = "profile_display.add_profile.input_error_empty"
         static let inputLabel = "profile_display.add_profile.input_label"
         static let inputPlaceholder = "profile_display.add_profile.input_placeholder"
         static let kidsModeDescription = "profile_display.add_profile.kids_mode_description"
         static let kidsModeTitle = "profile_display.add_profile.kids_mode_title"
         static let title = "profile_display.add_profile.title"
         static let titleDescription = "profile_display.add_profile.title_description"
         static let titleProfileSettings = "profile_display.add_profile.title_profile_settings"
      }

      struct Button {
         static let cancel = "profile_display.button.cancel"
         static let create = "profile_display.button.create"
         static let deleteProfile = "profile_display.button.delete_profile"
      }

      struct ChangeAvatar {
         static let description = "profile_display.change_avatar.description"
         static let title = "profile_display.change_avatar.title"
      }

      struct EditProfile {
         static let displayLanguage = "profile_display.edit_profile.display_language"
         static let kidsModeDescription = "profile_display.edit_profile.kids_mode_description"
         static let kidsModeStatusOff = "profile_display.edit_profile.kids_mode_status_off"
         static let kidsModeStatusOn = "profile_display.edit_profile.kids_mode_status_on"
         static let kidsModeTitle = "profile_display.edit_profile.kids_mode_title"
         static let profileNameInputError = "profile_display.edit_profile.profile_name_input_error"
         static let profileNameInputLabel = "profile_display.edit_profile.profile_name_input_label"
         static let title = "profile_display.edit_profile.title"
         static let titleDescription = "profile_display.edit_profile.title_description"

         struct DisplayLanguage {
            static let title = "profile_display.edit_profile.display_language.title"
            static let titleDiscription = "profile_display.edit_profile.display_language.title_discription"
         }
      }

      struct Otp {
         static let comfirmButton = "profile_display.otp.comfirm_button"
         static let desOtp = "profile_display.otp.des_otp"
         static let resendButton = "profile_display.otp.resend_button"
         static let titleOtp = "profile_display.otp.title_otp"

         struct Error {
            static let otpExpired = "profile_display.otp.error.otp_expired"
            static let tooManyFailed = "profile_display.otp.error.too_many_failed"
            static let vaildOtp = "profile_display.otp.error.vaild_otp"
         }
      }

      struct Pin {
         static let pinErrorProfileLocked = "profile_display.pin.pin_error_profile_locked"
         static let pinNotValid = "profile_display.pin.pin_not_valid"
         static let title = "profile_display.pin.title"
         static let titleDescription = "profile_display.pin.title_description"
      }

      struct ProfileSelection {
         static let addProfile = "profile_display.profile_selection.add_profile"
         static let doneButton = "profile_display.profile_selection.done_button"
         static let editButton = "profile_display.profile_selection.edit_button"
         static let kidsBadge = "profile_display.profile_selection.kids_badge"
         static let kidsProfileName = "profile_display.profile_selection.kids_profile_name"
         static let title = "profile_display.profile_selection.title"
         static let titleSwitchProfiles = "profile_display.profile_selection.title_switch_profiles"
      }

      struct SnackBar {
         static let createdProfileError = "profile_display.snack_bar.created_profile_error"
         static let createdProfileSuccess = "profile_display.snack_bar.created_profile_success"
         static let displayLanguageUpdateError = "profile_display.snack_bar.display_language_update_error"
         static let displayLanguageUpdateSuccess = "profile_display.snack_bar.display_language_update_success"
         static let pinErrorApi = "profile_display.snack_bar.pin_error_api"
         static let profileAvatarUpdateError = "profile_display.snack_bar.profile_avatar_update_error"
         static let profileAvatarUpdateSuccess = "profile_display.snack_bar.profile_avatar_update_success"
         static let profileNameUpdateError = "profile_display.snack_bar.profile_name_update_error"
         static let profileNameUpdateSuccess = "profile_display.snack_bar.profile_name_update_success"
         static let removeProfileError = "profile_display.snack_bar.remove_profile_error"
         static let removeProfileSuccess = "profile_display.snack_bar.remove_profile_success"
         static let somethingWentWrong = "profile_display.snack_bar.something_went_wrong"
      }
   }

   struct ScanQr {
      static let scanQrTitle = "scan_qr.scan_qr_title"
   }

   struct Search {
      static let clearButton = "search.clear_button"
      static let emptyDesc = "search.empty_desc"
      static let emptyTitle = "search.empty_title"
      static let inputPlaceholder = "search.input_placeholder"
   }

   struct SignInQr {
      static let languageButton = "sign_in_qr.language_button"
      static let logInDesc = "sign_in_qr.log_in_desc"
      static let qrError = "sign_in_qr.qr_error"
      static let qrSessionExpired = "sign_in_qr.qr_session_expired"
      static let title = "sign_in_qr.title"
   }

   struct SubtitlesAndAudio {
      static let audio = "subtitles_and_audio.audio"
      static let cn = "subtitles_and_audio.cn"
      static let en = "subtitles_and_audio.en"
      static let enAudio = "subtitles_and_audio.en_audio"
      static let enCc = "subtitles_and_audio.en_cc"
      static let enOriginal = "subtitles_and_audio.en_original"
      static let gm = "subtitles_and_audio.gm"
      static let id = "subtitles_and_audio.id"
      static let jp = "subtitles_and_audio.jp"
      static let kh = "subtitles_and_audio.kh"
      static let ko = "subtitles_and_audio.ko"
      static let my = "subtitles_and_audio.my"
      static let offButton = "subtitles_and_audio.off_button"
      static let original = "subtitles_and_audio.original"
      static let other = "subtitles_and_audio.other"
      static let phCebuano = "subtitles_and_audio.ph_cebuano"
      static let phFilipino = "subtitles_and_audio.ph_filipino"
      static let subtitles = "subtitles_and_audio.subtitles"
      static let th = "subtitles_and_audio.th"
      static let vn = "subtitles_and_audio.vn"
   }

   struct Suffix {
      static let episode = "suffix.episode"
      static let episodes = "suffix.episodes"
      static let season = "suffix.season"
      static let seasons = "suffix.seasons"
      static let title = "suffix.title"
      static let titles = "suffix.titles"
   }

   struct TermsAndCondition {
      static let acceptButton = "terms_and_condition.accept_button"
      static let accpetButton = "terms_and_condition.accpet_button"
      static let checkboxAccpetAll = "terms_and_condition.checkbox_accpet_all"
      static let confirm = "terms_and_condition.confirm"
      static let declineButton = "terms_and_condition.decline_button"
      static let inputEnterEmail = "terms_and_condition.input_enter_email"
      static let personalData = "terms_and_condition.personal_data"
      static let scroollButton = "terms_and_condition.scrooll_button"
      static let title = "terms_and_condition.title"
      static let titleMarketingConsent = "terms_and_condition.title_marketing_consent"
      static let titlePrivacyPolicy = "terms_and_condition.title_privacy_policy"
      static let titleSubscription = "terms_and_condition.title_subscription"
   }

   struct TvHomepage {
      static let liveTime = "tv_homepage.live_time"
      static let premiumTv = "tv_homepage.premium_tv"
      static let remindedMeButton = "tv_homepage.reminded_me_button"
      static let remindedSetButton = "tv_homepage.reminded_set_button"
      static let streaming = "tv_homepage.streaming"
      static let watchNowButton = "tv_homepage.watch_now_button"
   }

   struct TvNavigationDrawer {
      static let exitButton = "tv_navigation_drawer.exit_button"
      static let homeMenu = "tv_navigation_drawer.home_menu"
      static let liveTvMenu = "tv_navigation_drawer.live_tv_menu"
      static let moviesMenu = "tv_navigation_drawer.movies_menu"
      static let myListsMenu = "tv_navigation_drawer.my_lists_menu"
      static let newOnNowMenu = "tv_navigation_drawer.new_on_now_menu"
      static let profileMenu = "tv_navigation_drawer.profile_menu"
      static let searchMenu = "tv_navigation_drawer.search_menu"
      static let seriesMenu = "tv_navigation_drawer.series_menu"
      static let settingButton = "tv_navigation_drawer.setting_button"
      static let sportsMenu = "tv_navigation_drawer.sports_menu"
      static let switchProfile = "tv_navigation_drawer.switch_profile"
   }
}
